import { keccak256, toBytes } from "viem";

export const ROLES = {
  DEFAULT_ADMIN_ROLE: "0x0000000000000000000000000000000000000000000000000000000000000000",
  PIECE_MANAGER: keccak256(toBytes("PIECE_MANAGER")),
  PIECE_MINTER: keccak256(toBytes("PIECE_MINTER")),
  PIECE_AUDITOR: keccak256(toBytes("PIECE_AUDITOR")),
  PIECE_VALIDATOR: keccak256(toBytes("PIECE_VALIDATOR")),
  PIECE_DOCUMENT_MANAGER: keccak256(toBytes("PIECE_DOCUMENT_MANAGER")),
  ASSEMBLY_MANAGER: keccak256(toBytes("ASSEMBLY_MANAGER")),
  ASSEMBLY_MINTER: keccak256(toBytes("ASSEMBLY_MINTER")),
  ASSEMBLY_AUDITOR: keccak256(toBytes("ASSEMBLY_AUDITOR")),
  ASSEMBLY_VALIDATOR: keccak256(toBytes("ASSEMBLY_VALIDATOR")),
  ASSEMBLY_DOCUMENT_MANAGER: keccak256(toBytes("ASSEMBLY_DOCUMENT_MANAGER")),
  EQUIPMENT_MANAGER: keccak256(toBytes("EQUIPMENT_MANAGER")),
  EQUIPMENT_MINTER: keccak256(toBytes("EQUIPMENT_MINTER")),
  EQUIPMENT_AUDITOR: keccak256(toBytes("EQUIPMENT_AUDITOR")),
  EQUIPMENT_VALIDATOR: keccak256(toBytes("EQUIPMENT_VALIDATOR")),
  EQUIPMENT_DOCUMENT_MANAGER: keccak256(toBytes("EQUIPMENT_DOCUMENT_MANAGER")),
  TEMPLATE_MANAGER: keccak256(toBytes("TEMPLATE_MANAGER")),
  REGULATOR: keccak256(toBytes("REGULATOR")),
} as const;

export type RoleKey = keyof typeof ROLES;