name: NextJS Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: NextJS Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.1"
          cache: 'npm'
          cache-dependency-path: front/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build with Next.js
        run: npm run build
        #env:
        #  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: {{ secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID || 'placeholder_project_id_for_build_testing' }}